#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-LineTrace
version:      0.1.5
version_from: lib/Devel/LineTrace.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_08
